# Generated by Django 6.0 on 2026-01-31 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_postedithistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='homecontent',
            name='hero_column_one_image',
            field=models.ImageField(blank=True, help_text='Optional image for the first column', null=True, upload_to='site/'),
        ),
        migrations.AddField(
            model_name='homecontent',
            name='hero_column_one_text',
            field=models.TextField(blank=True, help_text='Optional text for the first column', null=True),
        ),
    ]
