# Generated by Django 6.0 on 2026-01-31 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_homecontent_hero_column_one_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homecontent',
            name='hero_column_three_content',
            field=models.TextField(blank=True, help_text='Content for the third column (optional)', null=True),
        ),
        migrations.AddField(
            model_name='homecontent',
            name='hero_column_two_heading',
            field=models.CharField(blank=True, help_text='Main heading for the middle column', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homecontent',
            name='hero_column_two_motto',
            field=models.TextField(blank=True, help_text='Sub-motto for the middle column', null=True),
        ),
    ]
