"""
Django settings for portfolio project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-)u#$d+ek^oum8)ivu%k@hvh#!kh$ekjee6mgu@n1bnnfobu4ss'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
    'admin_reorder',

    # Third party
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'ckeditor',
    'ckeditor_uploader',
]

# CKEditor Configuration
CKEDITOR_UPLOAD_PATH = "uploads/"
CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'full',
        'height': 300,
        'width': '100%',
        'uiColor': '#222222', # Darker toolbar
        'contentsCss': ['/static/css/ckeditor_custom.css'], # Custom editing area CSS
        'bodyClass': 'dark-editor',
    },
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'admin_reorder.middleware.ModelAdminReorder',
]

ADMIN_REORDER = (
    # 1. User Submissions
    {
        'app': 'submissions',
        'label': 'User Submissions',
        'models': (
            'core.ServiceBooking',
            'core.ContactMessage',
        )
    },
    
    # 2. User Management
    'auth',

    # --- PORTFOLIO CONTENT (10 Menus) ---

    # Menu 1
    {
        'app': 'menu_navbar',
        'label': '01. Navbar Content', 
        'models': ('core.NavbarSettings',)
    },
    
    # Menu 2
    {
        'app': 'menu_hero',
        'label': '02. Hero Section Content', 
        'models': (
            'core.HeroMainSettings',
            'core.HeroSocialSettings',
        )
    },
    
    # Menu 3
    {
        'app': 'menu_about',
        'label': '03. About Me Content',
        'models': (
            'core.AboutSectionSettings',
            'core.AcademicBackground',
        )
    },
    
    # Menu 4
    {
        'app': 'menu_experience',
        'label': '04. My Experience Content',
        'models': ('core.Experience',)
    },
    
    # Menu 5
    {
        'app': 'menu_expertise',
        'label': '05. My Expertise Content',
        'models': (
            'core.SkillCategory',
            'core.ProfessionalTrainingModel',
            'core.GlobalCertificationModel',
        )
    },
    
    # Menu 6
    {
        'app': 'menu_projects',
        'label': '06. Featured Projects Content',
        'models': ('core.Project',)
    },
    
    # Menu 7
    {
        'app': 'menu_services',
        'label': '07. My Services Content',
        'models': ('core.Service',)
    },
    
    # Menu 8
    {
        'app': 'menu_blog',
        'label': '08. My Blog Content',
        'models': (
            'core.BlogSectionSettings',
            'core.BlogPost',
        )
    },
    
    # Menu 9
    {
        'app': 'menu_contact',
        'label': '09. Contact',
        'models': ('core.ContactSectionSettings',)
    },
    
    # Menu 10
    {
        'app': 'menu_footer',
        'label': '10. Footer Content',
        'models': ('core.FooterSettings',)
    },
)

ROOT_URLCONF = 'portfolio.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',

            ],
        },
    },
]

WSGI_APPLICATION = 'portfolio.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Dhaka'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Auth settings
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

SITE_ID = 1
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_USERNAME_REQUIRED = True
ACCOUNT_AUTHENTICATION_METHOD = 'username_email'
ACCOUNT_EMAIL_VERIFICATION = 'none'
ACCOUNT_USERNAME_MIN_LENGTH = 1
LOGIN_REDIRECT_URL = '/blog/'
LOGOUT_REDIRECT_URL = '/blog/'

# Email configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'sandipdas050@gmail.com'
EMAIL_HOST_PASSWORD = 'fglz umhr gbyy vlzu'
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
