# Generated by Django 6.0.2 on 2026-02-15 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(default='Portfolio', max_length=100)),
                ('logo', models.ImageField(blank=True, help_text='Upload your logo here', upload_to='site/')),
                ('favicon', models.ImageField(blank=True, upload_to='site/')),
                ('hero_greeting', models.CharField(default='Hello, I am', max_length=100)),
                ('hero_name', models.CharField(default='Your Name', max_length=100)),
                ('hero_subtitle', models.CharField(default='Software Engineer', max_length=100)),
                ('hero_description', models.TextField(blank=True)),
                ('hero_bg_image', models.ImageField(blank=True, help_text='Background image for hero section', upload_to='hero/')),
                ('hero_profile_image', models.ImageField(blank=True, help_text='Your transparent profile picture', upload_to='hero/')),
                ('resume_file', models.FileField(blank=True, help_text='Your CV/Resume', upload_to='docs/')),
                ('about_title', models.CharField(default='About Me', max_length=100)),
                ('about_description', models.TextField(blank=True)),
                ('about_image', models.ImageField(blank=True, upload_to='about/')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('footer_copyright', models.CharField(default='© 2026 All Rights Reserved.', max_length=200)),
            ],
            options={
                'verbose_name': 'Home Page Content',
                'verbose_name_plural': 'Home Page Content',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='projects/')),
                ('tech_stack', models.CharField(help_text='Comma separated technologies', max_length=200)),
                ('live_link', models.URLField(blank=True)),
                ('repo_link', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='skills/')),
            ],
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(max_length=50)),
                ('icon_class', models.CharField(help_text="Font Awesome class, e.g., 'fab fa-github'", max_length=50)),
                ('url', models.URLField()),
            ],
        ),
    ]
