# Generated by Django 6.0.2 on 2026-02-15 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homesettings',
            name='facebook_url',
            field=models.URLField(blank=True, help_text='Facebook Profile URL'),
        ),
        migrations.AddField(
            model_name='homesettings',
            name='github_url',
            field=models.URLField(blank=True, help_text='GitHub Profile URL'),
        ),
        migrations.AddField(
            model_name='homesettings',
            name='instagram_url',
            field=models.URLField(blank=True, help_text='Instagram Profile URL'),
        ),
        migrations.AddField(
            model_name='homesettings',
            name='linkedin_url',
            field=models.URLField(blank=True, help_text='LinkedIn Profile URL'),
        ),
        migrations.AddField(
            model_name='homesettings',
            name='x_url',
            field=models.URLField(blank=True, help_text='X (Twitter) Profile URL'),
        ),
    ]
