# Generated by Django 6.0.2 on 2026-02-15 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_homesettings_facebook_url_homesettings_github_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['order', 'name']},
        ),
        migrations.AddField(
            model_name='skill',
            name='description',
            field=models.TextField(blank=True, help_text='Brief description of your proficiency in this skill'),
        ),
        migrations.AddField(
            model_name='skill',
            name='icon_class',
            field=models.CharField(blank=True, help_text="Font Awesome icon class (e.g., 'fas fa-code')", max_length=50),
        ),
        migrations.AddField(
            model_name='skill',
            name='order',
            field=models.IntegerField(default=0, help_text='Display order (lower numbers appear first)'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='image',
            field=models.ImageField(blank=True, help_text='Skill logo/icon image', upload_to='skills/'),
        ),
    ]
