# Generated by Django 6.0.2 on 2026-02-16 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_skillcategory_alter_project_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homesettings',
            name='projects_description',
            field=models.TextField(blank=True, help_text='Intro text for the Featured Projects section'),
        ),
    ]
