# Generated by Django 6.0.2 on 2026-02-16 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='core/company_logos/'),
        ),
        migrations.AlterField(
            model_name='homesettings',
            name='about_image',
            field=models.ImageField(blank=True, upload_to='core/about/'),
        ),
        migrations.AlterField(
            model_name='homesettings',
            name='favicon',
            field=models.ImageField(blank=True, upload_to='core/site/'),
        ),
        migrations.AlterField(
            model_name='homesettings',
            name='hero_bg_image',
            field=models.ImageField(blank=True, help_text='Background image for hero section', upload_to='core/hero/'),
        ),
        migrations.AlterField(
            model_name='homesettings',
            name='hero_profile_image',
            field=models.ImageField(blank=True, help_text='Your transparent profile picture', upload_to='core/hero/'),
        ),
        migrations.AlterField(
            model_name='homesettings',
            name='logo',
            field=models.ImageField(blank=True, help_text='Upload your logo here', upload_to='core/site/'),
        ),
        migrations.AlterField(
            model_name='homesettings',
            name='resume_file',
            field=models.FileField(blank=True, help_text='Your CV/Resume', upload_to='core/docs/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to='core/projects/'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='image',
            field=models.ImageField(blank=True, help_text='Skill logo/icon image', upload_to='core/skills/'),
        ),
    ]
