# Generated by Django 6.0.2 on 2026-02-16 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_experience_company_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='dominant_color',
            field=models.CharField(blank=True, default='', help_text='Auto-extracted from image. Hex color e.g. #3776AB', max_length=7),
        ),
    ]
