# Generated by Django 6.0.2 on 2026-02-16 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicBackground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(max_length=200)),
                ('institution_logo', models.ImageField(blank=True, null=True, upload_to='core/academic/')),
                ('degree_name', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Bullet points separated by new lines')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Academic Background',
                'ordering': ['order', 'institution_name'],
            },
        ),
        migrations.CreateModel(
            name='ProfessionalTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=200)),
                ('organization_name', models.CharField(max_length=200)),
                ('mode', models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline')], default='Online', max_length=20)),
                ('certification_link', models.URLField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Professional Training & Certifications',
                'ordering': ['order', 'course_name'],
            },
        ),
    ]
