# Generated by Django 6.0.2 on 2026-02-17 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_academicbackground_professionaltraining'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionaltraining',
            name='image',
            field=models.ImageField(blank=True, help_text='Certificate or Organization Logo', null=True, upload_to='core/training/'),
        ),
    ]
