# Generated by Django 6.0.2 on 2026-02-17 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_professionaltraining_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homesettings',
            name='about_image',
        ),
        migrations.AddField(
            model_name='homesettings',
            name='about_who_am_i',
            field=models.TextField(blank=True, help_text="Text for the 'Who am I?' section"),
        ),
    ]
