# Generated by Django 6.0.2 on 2026-02-17 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_homesettings_about_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('FOCUS', 'Professional Focus'), ('SKILL', 'Key Skills'), ('ROLE', 'Current Roles')], max_length=10)),
                ('text', models.CharField(max_length=200)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'About Me Items',
                'ordering': ['category', 'order'],
            },
        ),
    ]
