# Generated by Django 6.0.2 on 2026-02-17 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_aboutmeitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionaltraining',
            name='category',
            field=models.CharField(choices=[('TRAINING', 'Professional Training'), ('CERTIFICATION', 'Global Certification')], default='TRAINING', max_length=20),
        ),
    ]
