# Generated by Django 6.0.2 on 2026-02-17 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_professionaltraining_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalCertificationModel',
            fields=[
            ],
            options={
                'verbose_name': 'Global Certification',
                'verbose_name_plural': 'Global Certifications',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.professionaltraining',),
        ),
        migrations.CreateModel(
            name='ProfessionalTrainingModel',
            fields=[
            ],
            options={
                'verbose_name': 'Professional Training',
                'verbose_name_plural': 'Professional Trainings',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.professionaltraining',),
        ),
    ]
