# Generated by Django 6.0.2 on 2026-02-17 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_globalcertificationmodel_professionaltrainingmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicbackground',
            name='institution_link',
            field=models.URLField(blank=True, help_text='Website link of the institution'),
        ),
    ]
