# Generated by Django 6.0.2 on 2026-02-17 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_academicbackground_institution_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='core/blog/')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AboutSectionSettings',
            fields=[
            ],
            options={
                'verbose_name': 'About Section Content',
                'verbose_name_plural': 'About Section Content',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.homesettings',),
        ),
        migrations.CreateModel(
            name='BlogSectionSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Blog Section Content',
                'verbose_name_plural': 'Blog Section Content',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.homesettings',),
        ),
        migrations.CreateModel(
            name='ContactSectionSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Contact Section Info',
                'verbose_name_plural': 'Contact Section Info',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.homesettings',),
        ),
        migrations.CreateModel(
            name='FooterSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Footer Content',
                'verbose_name_plural': 'Footer Content',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.homesettings',),
        ),
        migrations.CreateModel(
            name='HomeSectionSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Home Section Content',
                'verbose_name_plural': 'Home Section Content',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.homesettings',),
        ),
        migrations.CreateModel(
            name='NavbarSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Navbar & Site Config',
                'verbose_name_plural': 'Navbar & Site Config',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.homesettings',),
        ),
        migrations.CreateModel(
            name='TextContentSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Section Descriptions',
                'verbose_name_plural': 'Section Descriptions',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.homesettings',),
        ),
        migrations.AddField(
            model_name='homesettings',
            name='blog_section_description',
            field=models.TextField(blank=True, help_text='About My Blog - shown under the My Blog container'),
        ),
        migrations.AddField(
            model_name='homesettings',
            name='blog_section_title',
            field=models.CharField(default='My Blog', max_length=100),
        ),
    ]
