# Generated by Django 6.0.2 on 2026-02-17 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_blogpost_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skillitem',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Skill Card Item', 'verbose_name_plural': 'Skill Card Items'},
        ),
    ]
