# Generated by Django 6.0.2 on 2026-02-17 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_skillitem_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertiseSectionSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Expertise Section Content',
                'verbose_name_plural': 'Expertise Section Content',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.homesettings',),
        ),
        migrations.AlterModelOptions(
            name='skillitem',
            options={'ordering': ['order', 'name']},
        ),
        migrations.AddField(
            model_name='skillcategory',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description for this skill category'),
        ),
    ]
