# Generated by Django 6.0.2 on 2026-02-17 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_expertisesectionsettings_alter_skillitem_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skillcategory',
            name='description',
        ),
    ]
