# Generated by Django 6.0.2 on 2026-02-18 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_blogpost_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='homesettings',
            name='facebook_logo',
            field=models.ImageField(blank=True, help_text='Facebook Logo (Transparent Background)', upload_to='core/social/'),
        ),
        migrations.AddField(
            model_name='homesettings',
            name='github_logo',
            field=models.ImageField(blank=True, help_text='GitHub Logo (Transparent Background)', upload_to='core/social/'),
        ),
        migrations.AddField(
            model_name='homesettings',
            name='instagram_logo',
            field=models.ImageField(blank=True, help_text='Instagram Logo (Transparent Background)', upload_to='core/social/'),
        ),
        migrations.AddField(
            model_name='homesettings',
            name='linkedin_logo',
            field=models.ImageField(blank=True, help_text='LinkedIn Logo (Transparent Background)', upload_to='core/social/'),
        ),
        migrations.AddField(
            model_name='homesettings',
            name='x_logo',
            field=models.ImageField(blank=True, help_text='X (Twitter) Logo (Transparent Background)', upload_to='core/social/'),
        ),
    ]
