# Generated by Django 6.0.2 on 2026-02-18 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_project_image_projectimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroMainSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Hero Main',
                'verbose_name_plural': 'Hero Main',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.homesettings',),
        ),
        migrations.CreateModel(
            name='HeroSocialSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Social Media',
                'verbose_name_plural': 'Social Media',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.homesettings',),
        ),
    ]
