# Generated by Django 6.0.2 on 2026-02-18 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_heromainsettings_herosocialsettings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GlobalCertificationModel',
        ),
        migrations.DeleteModel(
            name='HeroMainSettings',
        ),
        migrations.DeleteModel(
            name='HeroSocialSettings',
        ),
        migrations.DeleteModel(
            name='HomeSectionSettings',
        ),
        migrations.DeleteModel(
            name='ProfessionalTrainingModel',
        ),
        migrations.DeleteModel(
            name='TextContentSettings',
        ),
        migrations.CreateModel(
            name='HeroSectionSettings',
            fields=[
            ],
            options={
                'verbose_name': '02. Hero Section Content',
                'verbose_name_plural': '02. Hero Section Content',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.homesettings',),
        ),
        migrations.AlterModelOptions(
            name='aboutsectionsettings',
            options={'verbose_name': '03. About Me Content', 'verbose_name_plural': '03. About Me Content'},
        ),
        migrations.AlterModelOptions(
            name='blogsectionsettings',
            options={'verbose_name': '08. My Blog Content', 'verbose_name_plural': '08. My Blog Content'},
        ),
        migrations.AlterModelOptions(
            name='contactsectionsettings',
            options={'verbose_name': '09. Contact', 'verbose_name_plural': '09. Contact'},
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['-start_date'], 'verbose_name': '04. My Experience Content', 'verbose_name_plural': '04. My Experience Content'},
        ),
        migrations.AlterModelOptions(
            name='expertisesectionsettings',
            options={'verbose_name': '05. My Expertise Content', 'verbose_name_plural': '05. My Expertise Content'},
        ),
        migrations.AlterModelOptions(
            name='footersettings',
            options={'verbose_name': '10. Footer Content', 'verbose_name_plural': '10. Footer Content'},
        ),
        migrations.AlterModelOptions(
            name='navbarsettings',
            options={'verbose_name': '01. Navbar Content', 'verbose_name_plural': '01. Navbar Content'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at'], 'verbose_name': '06. Featured Projects Content', 'verbose_name_plural': '06. Featured Projects Content'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['order', 'title'], 'verbose_name': '07. My Services Content', 'verbose_name_plural': '07. My Services Content'},
        ),
        migrations.AlterModelOptions(
            name='servicebooking',
            options={'verbose_name': 'Service Booking', 'verbose_name_plural': 'Service Bookings'},
        ),
        migrations.AddField(
            model_name='academicbackground',
            name='settings',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='academic_backgrounds', to='core.homesettings'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='settings',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to='core.homesettings'),
        ),
        migrations.AddField(
            model_name='professionaltraining',
            name='settings',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='professional_trainings', to='core.homesettings'),
        ),
        migrations.AddField(
            model_name='skillcategory',
            name='settings',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='skill_categories', to='core.homesettings'),
        ),
        migrations.AlterField(
            model_name='academicbackground',
            name='institution_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='professionaltraining',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='core/training/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon_class',
            field=models.CharField(default='fas fa-layer-group', help_text='Font Awesome class', max_length=50),
        ),
        migrations.AlterField(
            model_name='skill',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='dominant_color',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
        migrations.AlterField(
            model_name='skill',
            name='icon_class',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='skill',
            name='image',
            field=models.ImageField(blank=True, upload_to='core/skills/'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='icon_class',
            field=models.CharField(max_length=50),
        ),
    ]
