# Generated by Django 6.0.2 on 2026-02-18 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_delete_globalcertificationmodel_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HeroSectionSettings',
        ),
        migrations.CreateModel(
            name='GlobalCertificationModel',
            fields=[
            ],
            options={
                'verbose_name': 'Global Certification',
                'verbose_name_plural': 'Global Certifications',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.professionaltraining',),
        ),
        migrations.CreateModel(
            name='HeroMainSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Hero Main',
                'verbose_name_plural': 'Hero Main',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.homesettings',),
        ),
        migrations.CreateModel(
            name='HeroSocialSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Social Media',
                'verbose_name_plural': 'Social Media',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.homesettings',),
        ),
        migrations.CreateModel(
            name='ProfessionalTrainingModel',
            fields=[
            ],
            options={
                'verbose_name': 'Professional Training',
                'verbose_name_plural': 'Professional Trainings',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.professionaltraining',),
        ),
        migrations.AlterModelOptions(
            name='aboutsectionsettings',
            options={'verbose_name': 'About Me Main', 'verbose_name_plural': 'About Me Main'},
        ),
        migrations.AlterModelOptions(
            name='blogsectionsettings',
            options={'verbose_name': 'Blog Section Description', 'verbose_name_plural': 'Blog Section Description'},
        ),
        migrations.AlterModelOptions(
            name='contactsectionsettings',
            options={'verbose_name': 'Contact Components', 'verbose_name_plural': 'Contact Components'},
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['-start_date']},
        ),
        migrations.AlterModelOptions(
            name='expertisesectionsettings',
            options={'verbose_name': 'Expertise Settings', 'verbose_name_plural': 'Expertise Settings'},
        ),
        migrations.AlterModelOptions(
            name='footersettings',
            options={'verbose_name': 'Footer Text', 'verbose_name_plural': 'Footer Text'},
        ),
        migrations.AlterModelOptions(
            name='navbarsettings',
            options={'verbose_name': 'Navbar Settings', 'verbose_name_plural': 'Navbar Settings'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['order', 'title']},
        ),
    ]
