# Generated by Django 6.0.2 on 2026-02-19 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_delete_herosectionsettings_globalcertificationmodel_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skillcategory',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Technical Skill', 'verbose_name_plural': 'Technical Skills'},
        ),
    ]
