# Generated by Django 6.0.2 on 2026-02-19 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_skillcategory_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicalSkillsSection',
            fields=[
            ],
            options={
                'verbose_name': 'Technical Skills',
                'verbose_name_plural': 'Technical Skills',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.homesettings',),
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Skill Card', 'verbose_name_plural': 'Skill Cards'},
        ),
        migrations.AlterModelOptions(
            name='skillcategory',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Skill Category List', 'verbose_name_plural': 'Skill Category Lists'},
        ),
        migrations.AddField(
            model_name='skill',
            name='settings',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='core.homesettings'),
        ),
        migrations.AddField(
            model_name='skillcategory',
            name='skills_list',
            field=models.TextField(blank=True, help_text='Comma-separated list of skills (e.g. Python, Django, AWS) to be displayed as buttons.'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='image',
            field=models.ImageField(upload_to='core/skills/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Technology Name'),
        ),
    ]
