# Generated by Django 6.0.2 on 2026-02-19 19:45

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_technicalskillssection_alter_skill_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skillcategory',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Skill Category Label', 'verbose_name_plural': 'Skill Category Labels'},
        ),
        migrations.AlterModelOptions(
            name='skillitem',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Skill Item', 'verbose_name_plural': 'Skill Items'},
        ),
        migrations.AlterField(
            model_name='homesettings',
            name='technical_skills_description',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Intro text for the Technical Skills section'),
        ),
    ]
