# Generated by Django 6.0.2 on 2026-02-19 20:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_alter_skillcategory_options_alter_skillitem_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('picture', models.ImageField(blank=True, help_text='Optional user picture', null=True, upload_to='core/reviews/')),
                ('rating', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(help_text='Short comment about the service')),
                ('is_approved', models.BooleanField(default=False, help_text='Only approved reviews will be displayed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'User Review',
                'verbose_name_plural': 'User Reviews',
                'ordering': ['-created_at'],
            },
        ),
    ]
