# Generated by Django 6.0.2 on 2026-02-19 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homesettings',
            name='technical_skills_description',
            field=models.TextField(blank=True, help_text='Intro text for the Technical Skills section'),
        ),
    ]
