# Generated by Django 6.0.2 on 2026-02-19 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_alter_homesettings_technical_skills_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='is_approved',
            field=models.BooleanField(default=True, help_text='Set to False to hide this review'),
        ),
    ]
