# Generated by Django 6.0.2 on 2026-02-20 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_alter_review_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
