# Generated by Django 6.0.2 on 2026-02-20 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_review_company_name_review_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='company_name',
            field=models.CharField(default='N/A', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='location',
            field=models.CharField(default='N/A', max_length=100),
            preserve_default=False,
        ),
    ]
