# Generated by Django 6.0.2 on 2026-02-20 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_alter_review_company_name_alter_review_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(help_text='Short comment about the service', max_length=50),
        ),
        migrations.AlterField(
            model_name='review',
            name='company_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='review',
            name='location',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='review',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
