# Generated by Django 6.0.2 on 2026-02-20 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_alter_review_comment_alter_review_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(help_text='Short comment about the service', max_length=70),
        ),
    ]
