# Generated by Django 6.0.2 on 2026-02-20 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_alter_review_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutMeItem',
        ),
        migrations.DeleteModel(
            name='SocialLink',
        ),
        migrations.DeleteModel(
            name='ExpertiseSectionSettings',
        ),
        migrations.RemoveField(
            model_name='skillcategory',
            name='skills_list',
        ),
    ]
