# Generated by Django 6.0.2 on 2026-02-20 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_delete_aboutmeitem_delete_sociallink_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homesettings',
            name='hero_subtitle',
        ),
    ]
