# Generated by Django 6.0.2 on 2026-02-20 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_remove_homesettings_hero_subtitle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactsectionsettings',
            options={'verbose_name': 'Contact Menu', 'verbose_name_plural': 'Contact Menu'},
        ),
        migrations.AddField(
            model_name='homesettings',
            name='contact_heading',
            field=models.CharField(default="Let's Connect!", max_length=100),
        ),
        migrations.AddField(
            model_name='homesettings',
            name='contact_sub_heading',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='homesettings',
            name='contact_text',
            field=models.TextField(blank=True, help_text='Text shown below the sub-heading'),
        ),
    ]
