# Generated by Django 6.0.2 on 2026-02-20 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_remove_homesettings_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navbarmenu',
            name='section_id',
            field=models.CharField(blank=True, editable=False, max_length=50),
        ),
    ]
