# Generated by Django 6.0.2 on 2026-02-20 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_alter_navbarmenu_section_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicebooking',
            name='preferred_date',
        ),
        migrations.DeleteModel(
            name='NavbarMenu',
        ),
    ]
