# Generated by Django 6.0.2 on 2026-02-23 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_remove_servicebooking_preferred_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicebooking',
            name='preferred_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='NavbarMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Menu Name')),
                ('section_id', models.CharField(blank=True, help_text="HTML ID (auto-generated if empty). Use: 'home', 'about', 'experience', 'skills', 'projects', 'service', 'blog', 'contact' for existing sections.", max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('settings', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='navbar_menus', to='core.homesettings')),
            ],
            options={
                'verbose_name': 'Menu Item',
                'verbose_name_plural': 'Menu Items',
                'ordering': ['order', 'name'],
            },
        ),
    ]
