# Generated by Django 6.0.2 on 2026-02-23 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_alter_blogpost_image_blogpostimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpostimage',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='blogpostimage',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
