# Generated by Django 6.0.2 on 2026-02-23 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_alter_blogpostimage_options_blogpostimage_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='image',
        ),
        migrations.RemoveField(
            model_name='blogpostimage',
            name='post',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='gallery',
            field=models.ManyToManyField(blank=True, help_text='Add multiple images using the plus (+) icon', related_name='posts', to='core.blogpostimage'),
        ),
    ]
