# Generated by Django 6.0.2 on 2026-02-23 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_remove_blogpost_image_remove_blogpostimage_post_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='gallery',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='images',
            field=models.ManyToManyField(blank=True, help_text='Upload or select multiple images using the plus (+) icon', related_name='posts', to='core.blogpostimage', verbose_name='Image'),
        ),
    ]
