# Generated by Django 6.0.2 on 2026-02-23 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_remove_blogpost_gallery_blogpost_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='images',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(blank=True, help_text='Main featured image for the post', null=True, upload_to='core/blog/', verbose_name='Image'),
        ),
        migrations.DeleteModel(
            name='BlogPostImage',
        ),
    ]
