# Generated by Django 6.0.2 on 2026-02-23 17:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_remove_blogpost_image_blogcomment_blogpostimage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogManagement',
            fields=[
            ],
            options={
                'verbose_name': 'Blog Management (Metrics & Visitors)',
                'verbose_name_plural': 'Blog Management (Metrics & Visitors)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.blogpost',),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, default='default_profile.png', null=True, upload_to='profiles/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
