# Generated by Django 6.0.2 on 2026-02-24 12:24

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0056_userprofile_contact_number_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogManagement',
        ),
        migrations.DeleteModel(
            name='BlogSectionSettings',
        ),
        migrations.CreateModel(
            name='UserManagement',
            fields=[
            ],
            options={
                'verbose_name': 'User Management',
                'verbose_name_plural': 'User Management',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-created_at'], 'verbose_name': 'Blog Site Management', 'verbose_name_plural': 'Blog Site Management'},
        ),
        migrations.AddField(
            model_name='blogviewtrack',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
