# Generated by Django 6.0.2 on 2026-02-25 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_pendingregistration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='company_name',
            new_name='profession',
        ),
    ]
