# Generated by Django 6.0.2 on 2026-03-01 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_rename_review_company_name_to_profession'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='organization',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
