# Generated by Django 6.0.2 on 2026-03-01 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_userprofile_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='homesettings',
            name='nav_icon',
            field=models.ImageField(blank=True, help_text='Small icon shown in the navigation bar', upload_to='core/site/'),
        ),
        migrations.AddField(
            model_name='homesettings',
            name='nav_name',
            field=models.CharField(default='Portfolio', help_text='The name shown in the navigation bar', max_length=100),
        ),
        migrations.AlterField(
            model_name='homesettings',
            name='logo',
            field=models.ImageField(blank=True, help_text='The main logo of the site', upload_to='core/site/'),
        ),
        migrations.AlterField(
            model_name='homesettings',
            name='site_title',
            field=models.CharField(default='Portfolio', help_text='Shown in the browser tab', max_length=100),
        ),
    ]
