# Generated by Django 6.0.2 on 2026-03-01 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_homesettings_nav_icon_homesettings_nav_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homesettings',
            name='nav_icon',
        ),
    ]
