# Generated by Django 6.0.2 on 2026-03-02 11:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_remove_homesettings_nav_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicebooking',
            name='preferred_date',
        ),
        migrations.RemoveField(
            model_name='servicebooking',
            name='preferred_time',
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='date_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='date_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='time_from',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='time_to',
            field=models.TimeField(default=datetime.time(10, 0)),
        ),
    ]
