# Generated by Django 6.0.2 on 2026-03-02 11:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_remove_servicebooking_preferred_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicebooking',
            name='date_from',
            field=models.DateField(blank=True, null=True, verbose_name='Booking Start Date'),
        ),
        migrations.AlterField(
            model_name='servicebooking',
            name='date_to',
            field=models.DateField(blank=True, null=True, verbose_name='Booking End Date'),
        ),
        migrations.AlterField(
            model_name='servicebooking',
            name='time_from',
            field=models.TimeField(default=datetime.time(9, 0), verbose_name='Booking Start Time'),
        ),
        migrations.AlterField(
            model_name='servicebooking',
            name='time_to',
            field=models.TimeField(default=datetime.time(10, 0), verbose_name='Booking End Time'),
        ),
    ]
