# Generated by Django 6.0.2 on 2026-03-02 11:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_alter_servicebooking_date_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicebooking',
            name='date_from',
            field=models.DateField(default=datetime.date.today, verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='servicebooking',
            name='date_to',
            field=models.DateField(default=datetime.date.today, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='servicebooking',
            name='time_from',
            field=models.TimeField(default=datetime.time(9, 0), verbose_name='Start Time'),
        ),
        migrations.AlterField(
            model_name='servicebooking',
            name='time_to',
            field=models.TimeField(default=datetime.time(10, 0), verbose_name='End Time'),
        ),
    ]
