# Generated by Django 6.0.2 on 2026-02-15 12:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myecom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('site_name', models.CharField(default='Sandwips E-Shop', max_length=255)),
                ('site_description', models.TextField(blank=True, default='The largest retail chain of computer shops in Bangladesh.')),
                ('support_phone', models.CharField(default='+880 1234 567 890', max_length=20)),
                ('support_email', models.EmailField(default='support@sandwips.com', max_length=254)),
                ('address', models.TextField(blank=True, default='Kusholi Bhaban, Agargaon, Dhaka-1207')),
                ('facebook_url', models.URLField(blank=True, default='#')),
                ('twitter_url', models.URLField(blank=True, default='#')),
                ('instagram_url', models.URLField(blank=True, default='#')),
                ('linkedin_url', models.URLField(blank=True, default='#')),
                ('youtube_url', models.URLField(blank=True, default='#')),
                ('footer_text', models.TextField(blank=True, help_text='Text to display in the footer bottom')),
                ('copyright_text', models.CharField(default='© 2026 Sandwips E-Shop. All rights reserved.', max_length=255)),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configuration',
            },
        ),
    ]
