# Generated by Django 6.0.2 on 2026-02-15 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myecom', '0002_siteconfiguration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='site_name',
            field=models.CharField(default='SANDWIPS', max_length=255),
        ),
    ]
